name: Publish Package

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  id-token: write # Required for OIDC
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.61.0-noble
      options: --user 1001
    # if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install pnpm, Node.js and dependencies
        uses: pnpm/setup@v3
        with:
          runtime: node@26
          cache: false

      # Ensure npm 11.5.1 or later is installed (required for Trusted Publishers)
      - name: Update npm
        run: npm install -g npm@latest

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm run build 

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Publish to NPM
        run: pnpm publish --access public

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ steps.package-version.outputs.version }}
          generate_release_notes: true
