name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm' # deactivate for local test

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # for local test with act (medium ubuntu image)
      # - run: pnpm exec playwright install --with-deps

      - name: Build lib
        run: pnpm run build

      - name: Run tests
        run: pnpm test
